project: 'Low Altitude Navigation'
name: bc
device: cuda

data:
  expert_demo_dir: /home/yixuany/Workspace/LowAltitudeFlight/deliverables/low_altitude_flight/expert_demonstrations/trajectories
  training_data_dir: /home/yixuany/Workspace/LowAltitudeFlight/deliverables/low_altitude_flight/expert_demonstrations/images
  img_size: [256, 256]
  training_data_ratio: 0.8
  num_traj: 1
  
train:
  num_epochs: 500
  batch_size: 32
  lr: 0.0001

model:
  state_dim: 3 # x,y,z
  out_seq_len: 10 # Number of steps in the future to predict
  modes: 3 # Modes of distribution
  